# Generated by Django 3.2.6 on 2021-09-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default=0, max_length=32, verbose_name='tel'),
            preserve_default=False,
        ),
    ]
