# Generated by Django 3.2.6 on 2021-09-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0002_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='username'),
        ),
    ]
