# Generated by Django 3.2.6 on 2021-09-25 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0005_follow_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='firstnmae_furi',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname_furi',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
