# Generated by Django 3.2.6 on 2021-09-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0006_auto_20210926_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portalcode', models.IntegerField()),
                ('detail1', models.TextField(max_length=30)),
                ('detail2', models.TextField(max_length=30)),
                ('detail3', models.TextField(max_length=30, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anty.prefectures')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
