# Generated by Django 3.2.6 on 2021-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0008_rename_myaddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tel',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
