# Generated by Django 3.2.6 on 2021-09-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0010_auto_20210926_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='firstnmae_furi',
            new_name='firstname_furi',
        ),
    ]
