# Generated by Django 3.2.6 on 2021-09-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0011_rename_firstnmae_furi_address_firstname_furi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmae', models.TextField(max_length=10)),
                ('line_id', models.TextField(max_length=30)),
                ('message_status', models.IntegerField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
