# Generated by Django 3.2.6 on 2021-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0012_line_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_user',
            name='nmae',
        ),
        migrations.AddField(
            model_name='line_user',
            name='name',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
