# Generated by Django 3.2.6 on 2021-09-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0013_auto_20210928_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_user',
            name='broadcast',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
