# Generated by Django 3.2.6 on 2021-10-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0014_line_user_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, null=True)),
                ('image_url', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, null=True)),
                ('image_url', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, null=True)),
                ('image_url', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
