# Generated by Django 3.2.6 on 2021-10-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0015_brand_category_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anty.brand')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anty.category')),
                ('gender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anty.gender')),
            ],
        ),
    ]
