# Generated by Django 3.2.6 on 2021-10-05 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0016_temp_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_used_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('intro', models.TextField(max_length=1000)),
                ('base_price', models.IntegerField()),
                ('image_url', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='used_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('explain', models.TextField(max_length=1000)),
                ('is_released', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL)),
                ('temp_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anty.temp_used_product')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gender',
            name='image_url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Temp_product',
        ),
        migrations.AddField(
            model_name='temp_used_product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anty.brand'),
        ),
        migrations.AddField(
            model_name='temp_used_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anty.category'),
        ),
        migrations.AddField(
            model_name='temp_used_product',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anty.gender'),
        ),
    ]
