# Generated by Django 3.2.6 on 2021-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0017_auto_20211005_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='code',
            field=models.BooleanField(default=False),
        ),
    ]
