# Generated by Django 3.2.6 on 2021-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0019_alter_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='image_url',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
