# Generated by Django 3.2.6 on 2021-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0021_remove_temp_used_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_used_product',
            name='intro',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
