# Generated by Django 3.2.6 on 2021-10-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0023_alter_used_product_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hope_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sche_hipping_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(max_length=10)),
            ],
        ),
    ]
