# Generated by Django 3.2.6 on 2021-10-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0024_hope_sell_product_status_sche_hipping_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sche_hipping_date',
            new_name='Sche_sipping_date',
        ),
    ]
