# Generated by Django 3.2.6 on 2021-10-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0025_rename_sche_hipping_date_sche_sipping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_product',
            name='hope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Anty.hope_sell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='used_product',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Anty.sche_sipping_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='used_product',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Anty.product_status'),
            preserve_default=False,
        ),
    ]
