# Generated by Django 3.2.6 on 2021-10-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0027_alter_used_product_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=1000)),
            ],
        ),
    ]
