# Generated by Django 3.2.6 on 2021-10-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0030_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_product_image',
            name='temp_used_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anty.used_product'),
        ),
    ]
