# Generated by Django 3.2.6 on 2021-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0032_rename_temp_used_product_used_product_image_used_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
