# Generated by Django 3.2.6 on 2021-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anty', '0036_auto_20211025_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='detail4',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='kana4',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
